name: Changelog updated

on:
  pull_request:
      branches:
        - master

jobs:
  check:
      name: Check that CHANGELOG.md has been modified
      runs-on: ubuntu-latest
      steps:
      - uses: nholden/modified-file-filter-action@master
        with:
          args: "CHANGELOG.md"