name: Changelog updated

on:
  pull_request:
      branches:
        - master

jobs:
  check:
      name: Check that CHANGELOG.md has been modified
      runs-on: ubuntu-latest
      steps:
      - run: cat $GITHUB_EVENT_PATH | jq -c '.pull_request.url + "/files"' | xargs curl --silent |  jq -c 'map(.filename)' | grep -q 'CHANGELOG.md'