name: Quicktest

on: push

jobs:
  test:
    name: Test on latest node and ubuntu versions
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use default Node.js version
      uses: actions/setup-node@v1.1.0
    - name: npm install and test
      run: |
        npm install
        npm test
